import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Basir',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Puma',
        logo: '/images/logo1.png',
        description: 'best seller',
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: 'Lance',
      email: 'wo@wo.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'Nike',
        logo: '/images/logo1.png',
        description: 'best seller',
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    // {
    //   name: 'Nike Slim Shirt',
    //   category: 'Shirts',
    //   image: '/images/p1.jpg',
    //   price: 120,
    //   countInStock: 10,
    //   brand: 'Nike',
    //   rating: 4.5,
    //   numReviews: 10,
    //   description: 'high quality product',
    // },
    // {
    //   name: 'Adidas Fit Shirt',
    //   category: 'Shirts',
    //   image: '/images/p2.jpg',
    //   price: 100,
    //   countInStock: 20,
    //   brand: 'Adidas',
    //   rating: 4.0,
    //   numReviews: 10,
    //   description: 'high quality product',
    // },
    // {
    //   name: 'Lacoste Free Shirt',
    //   category: 'Shirts',
    //   image: '/images/p3.jpg',
    //   price: 220,
    //   countInStock: 0,
    //   brand: 'Lacoste',
    //   rating: 4.8,
    //   numReviews: 17,
    //   description: 'high quality product',
    // },
    // {
    //   name: 'Nike Slim Pant',
    //   category: 'Pants',
    //   image: '/images/p4.jpg',
    //   price: 78,
    //   countInStock: 15,
    //   brand: 'Nike',
    //   rating: 4.5,
    //   numReviews: 14,
    //   description: 'high quality product',
    // },
    // {
    //   name: 'Puma Slim Pant',
    //   category: 'Pants',
    //   image: '/images/p5.jpg',
    //   price: 65,
    //   countInStock: 5,
    //   brand: 'Puma',
    //   rating: 4.5,
    //   numReviews: 10,
    //   description: 'high quality product',
    // },
    // {
    //   name: 'Adidas Fit Pant',
    //   category: 'Pants',
    //   image: '/images/p6.jpg',
    //   price: 139,
    //   countInStock: 12,
    //   brand: 'Adidas',
    //   rating: 4.5,
    //   numReviews: 15,
    //   description: 'high quality product',
    // },
    // {
    //   name: 'Adidas Dame',
    //   category: 'Shoes',
    //   image: '/images/Adidas_Dame.jpg',
    //   price: 170,
    //   countInStock: 67,
    //   brand: 'Adidas',
    //   rating: 3.8,
    //   numReviews: 365,
    //   description: 'high quality product',
    // },
    // {
    //   name: 'Adidas Trae',
    //   category: 'Shoes',
    //   image: '/images/Adidas_Trae.jpg',
    //   price: 1880,
    //   countInStock: 17,
    //   brand: 'Adidas',
    //   rating: 4.7,
    //   numReviews: 365,
    //   description: 'high quality product',
    // },
    // {
    //   name: 'NB Kawhi',
    //   category: 'Shoes',
    //   image: '/images/NB_Kawhi.jpg',
    //   price: 210,
    //   countInStock: 57,
    //   brand: 'NB',
    //   rating: 4.0,
    //   numReviews: 2,
    //   description: 'high quality product',
    // },
    // {
    //   name: 'Nike KD',
    //   category: 'Shoes',
    //   image: '/images/Nike_KD.jpg',
    //   price: 190,
    //   countInStock: 26,
    //   brand: 'Nike',
    //   rating: 2.7,
    //   numReviews: 19,
    //   description: 'high quality product',
    // },
    // {
    //   name: 'Nike Lebron',
    //   category: 'Shoes',
    //   image: '/images/Nike_Lebron.jpg',
    //   price: 210,
    //   countInStock: 37,
    //   brand: 'Nike',
    //   rating: 4.9,
    //   numReviews: 21,
    //   description: 'high quality product',
    // }
    {
      name: 'Puma Classics oversized hoodie in off white',
      category: 'Shirts',
      image: '/images/puma_shirt.png',
      price: 67,
      countInStock: 10,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Adidas Originals adicolor 3 stripe sweat in mauve',
      category: 'Shirts',
      image: '/images/adidas_shirt.png',
      price: 87,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Nike pull over fleece hoodie in pale coral',
      category: 'Shirts',
      image: '/images/nike_shirt.png',
      price: 106,
      countInStock: 0,
      brand: 'Nike',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      name: 'Puma Classics oversized sweatpants in brown',
      category: 'Pants',
      image: '/images/puma_pant.png',
      price: 60,
      countInStock: 15,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Adidas Training Earth Shades fleece tracksuit in brown',
      category: 'Pants',
      image: '/images/adidas_pant.png',
      price: 87,
      countInStock: 5,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Nike Club Sweatpants In Black',
      category: 'Pants',
      image: '/images/nike_pant.png',
      price: 88,
      countInStock: 12,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
  ],
};
export default data;
